version: '3.8'

services:
  portfolio:
    build: .
    container_name: prasanth-portfolio
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - ./letsencrypt:/etc/letsencrypt:ro
    networks:
      - web

networks:
  web:
    driver: bridge
